language: bash
dist: xenial

before_script:
  # Set up git user name and tag this commit
  - git config --global user.name "xiaoluhong"
  - git config --global user.email "xiaoluhong@rancher.com"
  - git config --global push.default simple

script:
  - bash scripts/sync-gitee.sh

services:
  - docker
before_install:
  - sudo apt-get update
  - sudo pip install shyaml
  - sudo apt-get install jq
  - docker login -u${ALI_DOCKER_USERNAME} -p${ALI_ DOCKER_PASSWORD}
  - chmod +x scripts/sync-img.sh
  - cd scripts && ./sync-img.sh
