language: bash

#env:
#  export GITEE_ACC=[secure]
#  export GITEE_PW=[secure]
#  export ALI_DOCKER_USERNAME=[secure]
#  export ALI_ DOCKER_PASSWORD=[secure]
#  export GITHUB_USERNAME=[secure]
#  export GITHUB_PASSWORD=[secure]

#before_deploy:
#      # Set up git user name and tag this commit
#      - git config --global user.name "xiaoluhong"
#      - git config --global user.email "xiaoluhong@rancher.com"
#      - git config --global push.default simple
#
before_script:
  # Set up git user name and tag this commit
  - git config --global user.name "xiaoluhong"
  - git config --global user.email "xiaoluhong@rancher.com"
  - git config --global push.default simple


script:
  - bash scripts/sync-gitee.sh


#deploy:
#  provider: script
#  skip_cleanup: true
#  script: bash scripts/sync-gitee.sh